### ISSUE TITLE
New tag?

### ISSUE THREAD

**Issue by abretaud** [erasche/docker-chado#5]
Hej,
Back to work!
Would it be possible to create a new tag for this chado image? The latest one (1.31-jenkins110-pg9.5) does not contain the #4 fix. So I use `latest` at the moment but I would feel better to use a pinned version in production
I don't know if it's worth making a new chado dump?

**Comment by hexylena** [comment]
Sometime (tm) soon I'll setup jenkins here and re-do chado dumps since those are needed and the old infra is aging / outside of my control.

free free to tag the new one that you need. should be on hub repo as well

**Comment by abretaud** [comment]
Ok for jenkins, cool if you can migrate it! (no hurry for me though)
The new tag is done, but the docker build was not triggered, maybe the complicated tag name did not match a regex somewhere? https://hub.docker.com/r/erasche/chado/builds/
Hope everything is ok for you on this side of the atlantic!

**Comment by abretaud** [comment]
Nevermind, it's online now :)
